# Generated by Django 5.0 on 2023-12-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='project_pdfs/'),
        ),
    ]
