# Generated by Django 5.0 on 2023-12-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pdf_file',
        ),
    ]
