# Generated by Django 5.0 on 2023-12-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('compani', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='certificate_images/')),
            ],
        ),
    ]
