# Generated by Django 5.0 on 2023-12-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
