# Generated by Django 5.0.1 on 2025-01-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_hots',
            field=models.URLField(blank=True),
        ),
    ]
